// $Id: VMS_EZ3T.h,v 1.1 2003/03/17 22:55:53 creigh Exp $
#ifndef _VMS_EZ3_T_H_ 
#define _VMS_EZ3_T_H_ 

#include "FineScaleT.h"

namespace Tahoe {

/** VMS_EZ3T: This class contains methods which build stiffness matricies 
 *  and formulate the non-linear Newton-Raphson equations Kd = -R
 *  for a Variational Multi-Scale (VMS) approach to implementation of Sandia's
 *  BCJ Model.  A dual field formulation u^alpha and u^beta is used. See
 *  Creighton et. al for more. 
 *  Collaboration:  Sandia National Laboratory and the University of Michigan **/


class VMS_EZ3T : public FineScaleT
{

	public:

  	enum B_T { 
						   	kB_1hat,  								
								kB05_tau_3hat,
								kB06_3hat,
								kBa_Cb_3hat,
							 	kBb_Cb_3hat,
							 	kBa_S,
							 	kBb_S,
	             	kNUM_B_TERMS };  // <-- Use for loops and count (KEEP THIS ONE LAST!!)

    enum A_T { 
						   	kgrad_ub,  
						   	kFa_n,  
						   	kCa_n,  
						   	kFai,  
						   	kFb,  
						   	kFbT,  
						   	kF_sharp,  
						   	kCb,  
						   	kEb,  
						   	kS,  
						   	kA1,  
						   	kDa_m,  
						   	kDa_mp1,  
						   	kG2,
	             	kNUM_A_TERMS };  // <-- Use for loops and count (KEEP THIS ONE LAST!!)

    enum T4_T { 	//	4th order tensors in reduced form 

								kCC,			//	Doubled upper case represent black bold font 
								kT4_Temp0,
	             	kNUM_T4_TERMS };  // <-- Use for loops and count (KEEP THIS ONE LAST!!)

						
   enum C_T { 
								kLamda,
								kMu,
								kf,
	             	kNUM_C_TERMS };  // <-- Use for loops and count (KEEP THIS ONE LAST!!)


		//--------------------------------------------------------------

 	VMS_EZ3T	(	) { }
								
	VMS_EZ3T	( FEA_ShapeFunctionT&, VMF_MaterialT*, VMS_VariableT&, VMS_VariableT&, 
							int &fTime_Step, double fdelta_t = 0.0, int IntegrationScheme = FEA::kBackward_Euler);

	void  Initialize	( int &in_ip, int &in_sd, int &in_en, int Initial_Time_Step=1 );

	void 	Construct 	( FEA_ShapeFunctionT&, VMF_MaterialT*, VMS_VariableT&, VMS_VariableT&, 
								 			int &fTime_Step, double fdelta_t = 0.0, int Integration_Scheme = FEA::kBackward_Euler); 

  void 	Form_LHS_Ka_Kb	(	dMatrixT &Ka, dMatrixT &Kb ); 
  void 	Form_RHS_F_int	(	dArrayT &F_int ); 
	void 	Form_B_List 		( void );  // Strain Displacement Matricies
	void 	Form_A_S_Lists 	( VMS_VariableT &np1, VMS_VariableT &n); // BCDE ---> A
	void 	Form_T4_List 		( void );  // Tensors generated by order reduction of 4th order Tensor
 	void 	Form_C_List 		( VMF_MaterialT *Iso_Matl );  // Constant List

	void  Get ( StringT &Name, FEA_dScalarT &scalar ) { scalar=0.0; cout<<"EZ3: Unknown scalar '"<<Name<<"' requested.\n"; }
	void  Get ( StringT &Name, FEA_dMatrixT &tensor );
	void 	Get ( int scalar_code, FEA_dScalarT &scalar  ) { scalar_code  = scalar.Length(); } //{scalar=S[scalar_code];} 
	void 	Get ( int tensor_code, FEA_dMatrixT &tensor, int tensor_order ) 		
							{ tensor = (tensor_order==2) ? A[tensor_code] : T4[tensor_code]; } 

	protected:

  	FEA_dMatrix_ArrayT    B; // Dimension: n_sd x n_sd*n_en , 		e.g. 9x24
		FEA_dMatrix_ArrayT    A; // Dimension: n_sd x n_sd , 					e.g. 3x3 
  	FEA_dMatrix_ArrayT   T4; 	// Dimension: n_sd*n_sd x n_sd*n_sd, e.g. 9x9 Matricies 
   	dArrayT 			      	C;

	protected:

		FEA_IntegrationT 		Integral;
		FEA_Data_ProcessorT Data_Pro; 

		int n_ip, n_rows, n_cols, n_sd, n_en, n_sd_x_n_sd, n_sd_x_n_en, Time_Integration_Scheme;
		double neg_1by10;
		int time_step;
		double delta_t;

};

} // namespace Tahoe 
#endif /* _VMS_EZ3T_H_ */

