/* $Id$ */
#ifndef _SOLID_MATERIALS_CONFIG_H_
#define _SOLID_MATERIALS_CONFIG_H_
/* This file was generated by MakeConfigHeaderFile.pl from SolidMaterialsConfig.conf */
/* created: Wed Jul 22 15:51:33 EDT 2015 */

/** \file SolidMaterialsConfig.h
 * Configuration of optional components within Tahoe.
 * Sections of the code are included or excluded in the build of Tahoe depending in 
 * this flags in this file and in the file SolidMaterialsConfig.make. Each option has
 * a #define definition in this file and a corresponding directory definition
 * in SolidMaterialsConfig.make. The two items must be set consistently to enable or
 * disable materials models. To enable an option:
 * -# in this file, uncomment the #define statement
 * -# in SolidMaterialsConfig.make, uncomment the macro.
 *
 * The naming convention for the definitions in this file and the macros in
 * SolidMaterialsConfig.make are as follows. For the option [OPTION]:
 * -# the symbol in this file will be [OPTION]
 * -# the macro defining the corresponding source directory will be DIRECTORY_[OPTION]
 */

/** \def CAUCHY_BORN_MATERIAL
 * Cauchy-Born crystal elasticity models.
 * This option must be set in conjunction with the DIRECTORY_CAUCHY_BORN_MATERIAL macro
 * in SolidMaterialsConfig.make. */
#define CAUCHY_BORN_MATERIAL 1

/** \def MODCBSW_MATERIAL
 * modified Cauchy-Born crystal elasticity models using the Stillinger-Weber potentials.
 * This option must be set in conjunction with the DIRECTORY_MODCBSW_MATERIAL macro
 * in SolidMaterialsConfig.make. */
#define MODCBSW_MATERIAL 1

/** \def VIB_MATERIAL
 * Virtual Internal Bond models.
 * This option must be set in conjunction with the DIRECTORY_VIB_MATERIAL macro
 * in SolidMaterialsConfig.make. */
#define VIB_MATERIAL 1

/** \def PLASTICITY_CRYSTAL_MATERIAL
 * Local and non-local crystal plasticity models.
 * This option must be set in conjunction with the DIRECTORY_PLASTICITY_CRYSTAL_MATERIAL macro
 * in SolidMaterialsConfig.make. */
#define PLASTICITY_CRYSTAL_MATERIAL 1

/** \def PLASTICITY_MACRO_MATERIAL
 * Local and non-local crystal plasticity models.
 * This option must be set in conjunction with the DIRECTORY_PLASTICITY_MACRO_MATERIAL macro
 * in SolidMaterialsConfig.make. */
#define PLASTICITY_MACRO_MATERIAL 1

/** \def ELASTICITY_CRYSTAL_MATERIAL
 * crystal elasticity models.
 * This option must be set in conjunction with the DIRECTORY_ELASTICITY_CRYSTAL_MATERIAL macro
 * in SolidMaterialsConfig.make. */
#define ELASTICITY_CRYSTAL_MATERIAL 1

/** \def PLASTICITY_J2_MATERIAL
 * J2 plasticity models.
 * This option must be set in conjunction with the DIRECTORY_PLASTICITY_J2_MATERIAL macro
 * in SolidMaterialsConfig.make. */
#define PLASTICITY_J2_MATERIAL 1

/** \def PLASTICITY_DP_MATERIAL
 * Drucker-Prager plasticity models.
 * This option must be set in conjunction with the DIRECTORY_PLASTICITY_DP_MATERIAL macro
 * in SolidMaterialsConfig.make. */
/* #define PLASTICITY_DP_MATERIAL 1 */

/** \def GEOMODEL_MATERIAL
 * Sandia Geomodel plasticity model.
 * This option must be set in conjunction with the DIRECTORY_GEOMODEL_MATERIAL macro
 * in SolidMaterialsConfig.make. */
#define GEOMODEL_MATERIAL 1

/** \def ABAQUS_MATERIAL
 * ABAQUS UMAT's and VUMAT's (requires the f2c module).
 * This option must be set in conjunction with the DIRECTORY_ABAQUS_MATERIAL macro
 * in SolidMaterialsConfig.make. */
/* #define ABAQUS_MATERIAL 1 */

/** \def THERMO_VISCO_PLASTIC_MATERIAL
 * Thermo-visco-plastic models.
 * This option must be set in conjunction with the DIRECTORY_THERMO_VISCO_PLASTIC_MATERIAL macro
 * in SolidMaterialsConfig.make. */
/* #define THERMO_VISCO_PLASTIC_MATERIAL 1 */

/** \def VISCOELASTICITY
 * Viscoelasticity models.
 * This option must be set in conjunction with the DIRECTORY_VISCOELASTICITY macro
 * in SolidMaterialsConfig.make. */
#define VISCOELASTICITY 1

/** \def SIERRA_MATERIAL
 * Models using the Sierra materials interface.
 * This option must be set in conjunction with the DIRECTORY_SIERRA_MATERIAL macro
 * in SolidMaterialsConfig.make. */
/* #define SIERRA_MATERIAL 1 */

#endif
