#!/usr/bin/env perl

if (!($ARGV[0]))
{
  print "\n";
  print "This program converts an encapsulated Postscript file to JPEG.\n";
  print "usage: eps2jpg input.ps [output.jpg]\n";
  print "\n";
  exit 1;
}

open f, "$ARGV[0]";
open g, ">/tmp/bound.ps";

if ($ARGV[1])
{
  $out = $ARGV[1];
}
else
{
  ($pre, $post) = split /\./, $ARGV[0];
  $out = "$pre".".jpg";
}

while (<f>)
{
  if (!(/^\%/))  
  {
    print g "0 0 $x3 $y3 rectclip\n";
    print g "-$x1 -$y1 translate\n";
    print g;
    while (<f>) { print g; }
  }
  else
  {
    if (/\%\%BoundingBox/)
    {
      ($onzin, $x1, $y1, $x2, $y2) = split / /;
      $x3 = "$x2" - "$x1";
      $y3 = "$y2" - "$y1";
      $gx = int "$x3"*600/72 + 0.9999;
      $gy = int "$y3"*600/72 + 0.9999;
      print g "%%BoundingBox: 0 0 $width $heigth\n";
      print "suggested pagesize $gx x $gy pixels\n";
    }
    else
    {
      print g;
    }
  }
}
close f;
close g;

$cmd = "gs -dNOPAUSE -dBATCH -sDEVICE=jpeg -g$gx"."x"."$gy -r600 -sOutputFile=$out /tmp/bound.ps\n";
print $cmd;
system($cmd);

