#!/usr/sbin/perl -w
#
# script to generate dbx instructions for loading a multiprocessor tahoe
# job running under the specified user 
#

if (scalar(@ARGV) != 2) {
  print STDOUT "\tusage: dbx_gen [login] [executable]\n";
  print STDOUT " generates dbx command files dbx_init and dbx_res\n";
  print STDOUT " to attach processes and resume execution\n";
	exit;	
}

$user = $ARGV[0];
$exec = $ARGV[1];

print STDOUT "user = $user\n";
print STDOUT "exec = $exec\n";

open(JOBS, "ps -U $user | grep $exec |") || die "could not execute ps";
open(INIT, ">dbx_init") || die "could not open file dbx_init";
open(RES, ">dbx_res") || die "could not open file dbx_res";

$count = 0;
while (defined($line = <JOBS>)) {
  chomp($line);
  if ($line =~ s/(\s+)(\d+)(.+)/$2/) {
	print STDOUT "adding PID ", $line, "\n";
	
	print INIT "set \$p$count = $line\n";
	print INIT "addproc \$p$count\n";
	print INIT "active \$p$count\n";
	print INIT "intercept all\n";
	
	print RES "active \$p$count\n";
	print RES "resume\n";
	$count++;
  }
}

