#!/usr/bin/perl -w
# $Id: toMacText,v 1.1 2002/02/02 18:54:03 paklein Exp $
# converts UNIX line endings to Mac line endings
# skips binary files and directories

# linebreak characters: \x0d - Mac, \x0a - Unix

if (scalar(@ARGV) == 0) {
	print STDOUT "\tusage: toMacText.pl [file1 file2 ...]\n";
}
else {
	foreach $oldFileName (@ARGV) {
	
		# file exists
		if (-e $oldFileName) {

			# is a directory
			if (-d $oldFileName) {
				print STDOUT "   skipping: $oldFileName (directory)\n";
			}
			# binary file		
			elsif (-B $oldFileName) {
				print STDOUT "   skipping: $oldFileName (binary)\n";
			}
			# is plain file
			elsif (-f $oldFileName) {
				# rename file to temp
				$inFileName = $oldFileName."___old";
				system("mv $oldFileName $inFileName");
	
				# open streams
				open(IN, $inFileName);
				open(OUT, ">".$oldFileName);	
	
				# convert lines endings
				print STDOUT "translating: $oldFileName\n";	
				while ($textFile = <IN>) {
					$textFile =~ s/\x0a/\x0d/g;
					print OUT $textFile;
				}
	
				# close streams
				close(IN); 
				close(OUT); 
			}
		}
		else {
			print STDOUT "file not found: $oldFileName\n";
		}
	}
}
