/* $Id: FCCPtsT.cpp,v 1.6 2011/12/01 21:11:38 bcyansfn Exp $ */
/* created: paklein (03/26/1999) */
#include "FCCPtsT.h"
#include <cmath>
#include "toolboxConstants.h"
#include "ExceptionT.h"

using namespace Tahoe;

const double Pi = acos(-1.0);

/* constructor */
FCCPtsT::FCCPtsT(int num_shells, double bond_length):
	fNumShells(num_shells),
	fBondLength(bond_length)
{
	const char caller[] = "FCCPtsT::FCCPtsT";

	/* number of nearest neighbor shells */
	if (fBondLength < 0.0) ExceptionT::BadInputValue(caller);
	
	int num_bonds;
	switch (fNumShells)
	{
		case 1:
			num_bonds = 6;
			break;
		default:
			ExceptionT::BadInputValue(caller, "currently only support nearest neighbor bonds");
	}	

	/* set weights */
	fJacobians.Dimension(num_bonds);
	fJacobians = 1;
}

/* generate sphere points:
*
*   theta = angle about z from x
*   phi   = angle about x from z
*
* The final orientation is generated by applied the
* theta and phi rotations in succession about the local
* axes */
const dArray2DT& FCCPtsT::SpherePoints(double phi_tr, double theta_tr)
{	
	/* set coordinates */
	SetCoords();
	
	/* reorient points */
	TransformPoints(phi_tr,theta_tr);
	
	return fPoints;
}

/* set lattice coordinates */
void FCCPtsT::SetCoords(void)
{
	/* vertex coordinate data */
	double p6[6*3] = { 1.0, 1.0, 0.0,
-1.0, 1.0, 0.0,
1.0, 0.0, 1.0,
-1.0, 0.0, 1.0,
0.0, 1.0, 1.0,
0.0,-1.0, 1.0};

	dArray2DT temp;
	switch (fNumShells)
	{
		case 1:		
			temp.Set(6,3,p6);
			break;
		default:
			ExceptionT::GeneralFail("FCCPtsT::SetCoords", "unsupported number of shells %d", fNumShells);
	}

	/* copy data */
	fPoints = temp;
	
	/* scale */
	fPoints /= fBondLength*sqrt(2.0);
}
