#!MC 1100
$!VarSet |MFBD| = ''
$!FIELDLAYERS SHOWMESH = NO
$!FIELDLAYERS SHOWEDGE = NO
$!GLOBALTHREEDVECTOR UVAR = 10
$!GLOBALTHREEDVECTOR VVAR = 11
$!GLOBALTHREEDVECTOR WVAR = 12
$!RESETVECTORLENGTH 
$!FIELDLAYERS SHOWVECTOR = YES
$!FIELDLAYERS USELIGHTINGEFFECT = NO
$!FIELDMAP [1-500]  VECTOR{COLOR = BLACK}
$!GLOBALTHREEDVECTOR USERELATIVE = NO
$!GLOBALTHREEDVECTOR USERELATIVE = YES
$!GLOBALTHREEDVECTOR RELATIVELENGTH = 0.4
$!RemoveVar |MFBD|

