#!MC 1100
$!VarSet |MFBD| = ''
$!FIELDLAYERS SHOWMESH = NO
$!FIELDLAYERS SHOWEDGE = NO
$!GLOBALTHREEDVECTOR UVAR = 4
$!GLOBALTHREEDVECTOR VVAR = 5
$!GLOBALTHREEDVECTOR WVAR = 6
$!RESETVECTORLENGTH 
$!FIELDLAYERS SHOWVECTOR = YES
$!FIELDLAYERS USELIGHTINGEFFECT = NO
$!FIELDMAP [1-500]  VECTOR{COLOR = BLACK}
$!GLOBALTHREEDVECTOR USERELATIVE = NO
$!GLOBALTHREEDVECTOR USERELATIVE = YES
$!GLOBALTHREEDVECTOR RELATIVELENGTH = 0.4
$!RemoveVar |MFBD|
