#!MC 1000
$!VarSet |MFBD| = ''
$!FIELDLAYERS SHOWBOUNDARY = NO
$!FIELDLAYERS SHOWSHADE = YES
$!FIELDLAYERS SHOWEDGE = YES
$!FIELDLAYERS SHOWMESH = NO
$!FRAMELAYOUT SHOWBORDER = NO
$!FIELDLAYERS USETRANSLUCENCY = NO
$!FIELD [1-500]  SHADE{COLOR = CUSTOM11}
$!FIELD [1-500]  SURFACEEFFECTS{LIGHTINGEFFECT = GOURAUD}
$!FIELD [1-500]  MESH{COLOR = CUSTOM41}
$!GLOBALTHREED LIGHTSOURCE{INCLUDESPECULAR = YES}
$!VIEW SETMAGNIFICATION
  MAGNIFICATION = 1
$!RemoveVar |MFBD|

